spring.application.name=barcamp-2024
spring.data.mongodb.uri=mongodb+srv://darvybm:TPnLn9Tz8Y9WXoC3@api-development.dbtab.mongodb.net/
spring.data.mongodb.database=api-development
server.port=${PORT:8080}

createFakeData=false
#fakeData.count=10